# This file was generated by GoReleaser. DO NOT EDIT.
cask "local-mirror" do
  version "2.3.1"

  on_macos do
    on_intel do
      sha256 "252ad06e96b30cb385655b70800e043355ba164bc39be74a91bcdc2302be5858"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e80d6eb0e33cddb295600c25e1128dea57fca23c76cca68f7a3e0cdda8f57258"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cf03689379a3ae4e3ea1fc8476b7655b733c566f5efefc52f957ca6c550660d2"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9976e70666590978e75ac2f628f6b2fed0a3ace30965177cb0fd7f8eb22434af"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_linux_arm64.tar.gz"
    end
  end

  name "local-mirror"
  desc "One-way directory mirroring over TCP with relays, LAN discovery and optional Noise encryption"
  homepage "https://github.com/xwvike/local-mirror"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "local-mirror"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/local-mirror"]
    end
  end

  # No zap stanza required

end
