# This file was generated by GoReleaser. DO NOT EDIT.
cask "local-mirror" do
  version "0.10.2"

  on_macos do
    on_intel do
      sha256 "5b01f6bab857a9fd4843817b20640efacc738c790f1a14ecb6f7d2ade2309bf0"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "06dd58723c1ec1172ed39b57923bfb1fd5766a31be22ba1aba92a9b5566b392f"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "04d2f5a0c27f1bcd5ede84188d27c2af599b56ed3ef5da3ccb950814ab1dbf1c"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "46e12069f29918db4ff469ef884d9017ffd60eeb34d47e247254ea053dbbf10c"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_linux_arm64.tar.gz"
    end
  end

  name "local-mirror"
  desc "One-way directory mirroring over TCP with relays, LAN discovery and optional Noise encryption"
  homepage "https://github.com/xwvike/local-mirror"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "local-mirror"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/local-mirror"]
    end
  end

  # No zap stanza required

end
