# This file was generated by GoReleaser. DO NOT EDIT.
cask "local-mirror" do
  version "2.6.1"

  on_macos do
    on_arm do
      sha256 "b0fd3b92cba31b13a396daa429e66c42762897353664ac231b52420d6361a59b"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "56ecf19a99cd6b91a1befd8d24775b212372d9d2fd6f7193aaf84c56bcc859ba"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "279499000493d63ada3dc00b0a38459cc59c8dfcee7efeda465c1ac68dded141"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0794d913f043e62b05f4cb7d854442c64c160d2370a92a913dafff8f7b3e7f63"
      url "https://github.com/xwvike/local-mirror/releases/download/v#{version}/local-mirror_#{version}_linux_amd64.tar.gz"
    end
  end

  name "local-mirror"
  desc "One-way directory mirroring over TCP with relays, LAN discovery and optional Noise encryption"
  homepage "https://github.com/xwvike/local-mirror"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "local-mirror"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/local-mirror"]
    end
  end

  # No zap stanza required
end
